[package]
name = "mommy-rs"
description = "mommy can now support you with ğŸª–type-safetyğŸª– and ğŸš€blazingly-fastğŸš€ speed~ â¤ï¸"
version = "0.1.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/natawie/mommy-rs"
keywords = ["mommy", "shell", "cli"]
categories = ["command-line-utilities"]
license = "Apache-2.0"

[dependencies]
ansi_term = "0.12.1"
clap = { version = "4.1.8", features = ["derive"] }
rand = "0.8.5"
